import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Decenza

// Value picker opened from the grindQuickSelect layout widget. A variable-RPM
// grinder's dial-in has two halves, so this shows up to two sections — a Grind
// section (always) and an RPM section (when the grinder is RPM-capable). Picking
// a row applies only that half. This is a plain VALUE picker — not a preset
// editor — so it is far simpler than RatioPresetDialog.
//
// Rows in each section are ordered fine -> coarse as generated by the item
// (smallest value / earliest letter / lowest RPM first). The grind section
// carries Finer (top) / Coarser (bottom) end labels when meaningful.
Dialog {
    id: root
    parent: Overlay.overlay
    anchors.centerIn: parent
    width: Math.min(Theme.scaled(360), parent ? parent.width * 0.95 : Theme.scaled(360))
    height: Math.min(contentCol.implicitHeight + Theme.scaled(40), parent ? parent.height * 0.92 : Theme.scaled(640))
    modal: true
    closePolicy: Dialog.CloseOnEscape | Dialog.CloseOnPressOutside
    padding: 0

    // [{ value: string, isCurrent: bool }] — fine -> coarse order, per section.
    property var grindRows: []
    property var rpmRows: []
    // Whether to show the grind section's finer/coarser end annotations.
    property bool finerHint: false

    signal grindPicked(string value)
    signal rpmPicked(string value)

    background: Rectangle {
        color: Theme.surfaceColor
        radius: Theme.cardRadius
        border.width: 1
        border.color: Theme.borderColor
    }

    // Reusable section: a header label, its rows, and (grind only) finer/coarser
    // end labels. `kind` picks which signal a tapped row fires.
    component PickerSection: ColumnLayout {
        id: section
        property string sectionLabel: ""
        property var rows: []
        property bool showEnds: false
        property string kind: "grind"    // "grind" | "rpm"
        Layout.fillWidth: true
        spacing: Theme.spacingSmall
        visible: rows.length > 0

        // --- Section header ---
        Text {
            Layout.fillWidth: true
            Layout.leftMargin: Theme.spacingLarge
            Layout.rightMargin: Theme.spacingLarge
            text: section.sectionLabel.toUpperCase()
            color: Theme.textColor
            font: Theme.subtitleFont
        }

        // --- Finer end label (grind only) ---
        Text {
            visible: section.showEnds && section.rows.length > 2
            Layout.fillWidth: true
            Layout.leftMargin: Theme.spacingLarge
            Layout.rightMargin: Theme.spacingLarge
            horizontalAlignment: Text.AlignHCenter
            text: TranslationManager.translate("grind.picker.finer", "Finer").toUpperCase()
            color: Theme.textSecondaryColor
            font: Theme.captionFont
        }

        // --- Value rows ---
        Repeater {
            model: section.rows
            delegate: Rectangle {
                id: rowRect
                required property var modelData
                readonly property bool isCurrent: modelData.isCurrent === true
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                Layout.preferredHeight: Theme.scaled(48)
                radius: Theme.buttonRadius
                color: rowMa.pressed ? Qt.darker(Theme.backgroundColor, 1.1) : Theme.backgroundColor
                border.width: isCurrent ? 2 : 1
                border.color: isCurrent ? Theme.primaryColor : Theme.borderColor

                Accessible.role: Accessible.Button
                Accessible.name: String(modelData.value)
                                 + (isCurrent ? ", " + TranslationManager.translate("grind.picker.current", "current") : "")
                Accessible.focusable: true
                Accessible.onPressAction: rowMa.clicked(null)

                RowLayout {
                    anchors.fill: parent
                    anchors.leftMargin: Theme.spacingMedium
                    anchors.rightMargin: Theme.spacingMedium
                    spacing: Theme.spacingSmall
                    Text {
                        text: String(rowRect.modelData.value)
                        color: rowRect.isCurrent ? Theme.primaryColor : Theme.textColor
                        font.pixelSize: Theme.scaled(20)
                        font.bold: rowRect.isCurrent
                    }
                    Item { Layout.fillWidth: true }
                    Text {
                        visible: rowRect.isCurrent
                        text: TranslationManager.translate("grind.picker.current", "current").toUpperCase()
                        color: Theme.primaryColor
                        font: Theme.captionFont
                    }
                }

                MouseArea {
                    id: rowMa
                    anchors.fill: parent
                    onClicked: {
                        if (section.kind === "rpm")
                            root.rpmPicked(String(rowRect.modelData.value))
                        else
                            root.grindPicked(String(rowRect.modelData.value))
                        root.close()
                    }
                }
            }
        }

        // --- Coarser end label (grind only) ---
        Text {
            visible: section.showEnds && section.rows.length > 2
            Layout.fillWidth: true
            Layout.leftMargin: Theme.spacingLarge
            Layout.rightMargin: Theme.spacingLarge
            horizontalAlignment: Text.AlignHCenter
            text: TranslationManager.translate("grind.picker.coarser", "Coarser").toUpperCase()
            color: Theme.textSecondaryColor
            font: Theme.captionFont
        }
    }

    contentItem: Flickable {
        contentWidth: width
        contentHeight: contentCol.implicitHeight
        clip: true
        boundsBehavior: Flickable.StopAtBounds
        ScrollBar.vertical: ScrollBar { policy: ScrollBar.AsNeeded }

        ColumnLayout {
            id: contentCol
            width: parent.width
            spacing: Theme.spacingMedium

            // --- Header ---
            ColumnLayout {
                Layout.fillWidth: true
                Layout.topMargin: Theme.spacingLarge
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                spacing: Theme.scaled(2)
                Text {
                    text: TranslationManager.translate("grind.picker.title", "Grind Setting")
                    color: Theme.textColor
                    font.pixelSize: Theme.scaled(24); font.bold: true
                }
                Text {
                    text: TranslationManager.translate("grind.picker.subtitle", "Tap a value to set the grinder")
                    color: Theme.textSecondaryColor
                    font: Theme.labelFont
                }
            }

            // --- Grind section ---
            PickerSection {
                sectionLabel: TranslationManager.translate("grind.quickSelect.label", "Grind")
                rows: root.grindRows
                showEnds: root.finerHint
                kind: "grind"
            }

            // --- RPM section (variable-RPM grinders) ---
            PickerSection {
                sectionLabel: TranslationManager.translate("grind.quickSelect.rpmLabel", "RPM")
                rows: root.rpmRows
                showEnds: false
                kind: "rpm"
            }

            // --- Empty state: no value could be generated. ---
            Text {
                visible: root.grindRows.length === 0 && root.rpmRows.length === 0
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
                text: TranslationManager.translate("grind.picker.empty",
                    "Set a grind value in Brew Settings first, then this list fills in around it.")
                color: Theme.textSecondaryColor
                font: Theme.bodyFont
            }

            // --- Close ---
            Rectangle {
                Layout.fillWidth: true
                Layout.leftMargin: Theme.spacingLarge
                Layout.rightMargin: Theme.spacingLarge
                Layout.bottomMargin: Theme.spacingLarge
                Layout.preferredHeight: Theme.scaled(48)
                radius: Theme.buttonRadius
                color: closeMa.pressed ? Qt.darker(Theme.primaryColor, 1.15) : Theme.primaryColor
                Accessible.role: Accessible.Button
                Accessible.name: TranslationManager.translate("common.button.close", "Close")
                Accessible.focusable: true
                Accessible.onPressAction: closeMa.clicked(null)
                Text {
                    anchors.centerIn: parent
                    text: TranslationManager.translate("common.button.close", "Close")
                    color: Theme.primaryContrastColor
                    font: Theme.bodyFont
                }
                MouseArea { id: closeMa; anchors.fill: parent; onClicked: root.close() }
            }
        }
    }
}
