.pragma library
// GENERATED by scripts/settings_search_index.py from the settings cards. Do not edit:
// change the card (or its SettingsSearch declaration) and rebuild.
var entries = [
    {"tabId": "machine", "cardId": "temperatureUnit", "kind": "card", "key": "settings.options.temperatureUnit", "fallback": "Temperature unit", "descKey": "settings.search.temperatureUnitDesc", "descFallback": "Show temperatures in Celsius or Fahrenheit", "keywords": ["fahrenheit", "celsius", "units", "°f", "°c", "degrees", "temperature"], "availability": ""},
    {"tabId": "machine", "cardId": "temperatureUnit", "kind": "adjustment", "key": "settings.options.showInFahrenheitAccessible", "fallback": "Show temperatures in Fahrenheit", "cardKey": "settings.options.temperatureUnit", "cardFallback": "Temperature unit", "keywords": [], "availability": ""},
]
