#pragma once

// QML registration for objects main() owns and used to publish with setContextProperty().
//
// WHY THIS FILE EXISTS SEPARATELY FROM THE CLASS HEADERS
// -----------------------------------------------------
// The obvious move is to put QML_ELEMENT straight in each class header, the way
// CoffeeBagStorage and the types reachable through MainController do it. That is fine for a
// header only the app compiles, and wrong for these: the classes here are also compiled into
// test and tool targets that link no Qt6::Qml. add_decenza_test() links Test/Core/Bluetooth/
// Sql/Network/Gui and nothing else, and `saw_parity` is narrower still — a <QtQml/...> include
// reaching either is a build break, not a style question. That is the same reason settings.h
// keeps its registration in settings_qml.h; this file is that pattern generalised.
//
// Only the Decenza target compiles this file (CMakeLists.txt), so the QtQml dependency stops
// here no matter how widely the underlying headers are included.
//
// WHY SINGLETONS RATHER THAN CONTEXT PROPERTIES
// ---------------------------------------------
// A context property is invisible to qmllint, qmlcachegen and the language server: the name
// resolves at runtime and at no other time. Every QML reference to one counts as an unqualified
// access, which is 943 warnings across these names — and, worse, is indistinguishable from a
// typo, because nothing in the build can tell the two apart. #1661 is what that costs when it
// goes wrong.
//
// LIFETIME — READ BEFORE ADDING AN ENTRY
// --------------------------------------
// Every object registered here MUST be declared before `QQmlApplicationEngine engine`
// (src/main.cpp) so it is destroyed after it. This is not a stylistic preference. A context
// property is dropped by QML when its object emits destroyed(), so publishing a short-lived
// object that way is survivable; a singleton published through a static raw pointer has no such
// mechanism, and nothing nulls it. main.cpp's teardown comment records a refractometer crash
// from exactly this ordering — the object died first while live bindings were still reading it.
//
// So: ghcSimulator, flowCalibrationModel and de1SimulatorPtr are declared after `engine` and are
// deliberately NOT here. Hoist the declaration first, then register.

#include <QtQml/qqmlregistration.h>
#include <QtQml/QQmlEngine>
#include <QtQml/QJSEngine>

#include "../ble/de1device.h"
#include "../screensaver/screensavervideomanager.h"

// Shared body of every create() below. The QML_* and Q_GADGET macros have to appear literally in
// each struct — moc does not expand preprocessor macros when it looks for them, so the structs
// cannot be generated by a macro — but the checked publish logic can be shared, and should be:
// three hand-written copies of it already exist and two of them differ in what they report.
template <typename T>
T* decenzaPublishedSingleton(T* instance, QJSEngine* engine, const char* qmlName)
{
    // Checked, not asserted. QT_FORCE_ASSERTS is only defined for sanitizer builds
    // (CMakeLists.txt), so Q_ASSERT compiles out of a shipped Release — and this is the one
    // condition where that matters: with the instance unpublished, create() returns null, every
    // reference to the name reads undefined, and nothing says why.
    if (!instance) {
        qCritical("%s: QML asked for the singleton before main() published it. Every binding on "
                  "this name will be undefined. Publish it before QQmlEngine::load().", qmlName);
        return nullptr;
    }
    if (engine->thread() != instance->thread()) {
        qCritical("%s: the QML engine and the instance are on different threads; QML property "
                  "access would be unsafe.", qmlName);
        return nullptr;
    }
    QJSEngine::setObjectOwnership(instance, QJSEngine::CppOwnership);
    return instance;
}

// 236 unqualified references across 26 QML files — the largest single name in the app.
// Also published to the GHC simulator window's second engine; a singleton covers both by
// construction, where the context property needed a second setContextProperty() call.
struct DE1DeviceForeign
{
    Q_GADGET
    QML_FOREIGN(DE1Device)
    QML_SINGLETON
    QML_NAMED_ELEMENT(DE1Device)

public:
    inline static DE1Device* s_singletonInstance = nullptr;
    static DE1Device* create(QQmlEngine*, QJSEngine* engine)
    {
        return decenzaPublishedSingleton(s_singletonInstance, engine, "DE1Device");
    }
};

// 179 references across 8 files. NOTE the name mismatch: the C++ class is
// ScreensaverVideoManager and QML has always called it ScreensaverManager, which is why this
// needs QML_NAMED_ELEMENT rather than QML_ELEMENT. Renaming either side is a separate change.
struct ScreensaverManagerForeign
{
    Q_GADGET
    QML_FOREIGN(ScreensaverVideoManager)
    QML_SINGLETON
    QML_NAMED_ELEMENT(ScreensaverManager)

public:
    inline static ScreensaverVideoManager* s_singletonInstance = nullptr;
    static ScreensaverVideoManager* create(QQmlEngine*, QJSEngine* engine)
    {
        return decenzaPublishedSingleton(s_singletonInstance, engine, "ScreensaverManager");
    }
};
