#!/usr/bin/env python3
"""Run qmllint over the QML tree and report what it found, per category and per file.

WHY THIS EXISTS, AND WHY IT PARSES BY COLUMN
--------------------------------------------
qmllint prints a warning line followed by the offending source line and a caret run:

    Warning: qml/Theme.qml:549:52: Unqualified access [unqualified]
        ... && LastShotChartSource.imageSource.length > 0)
               ^^^^^^^^^^^^^^^^^^^

The flagged identifier is NOT on the warning line — it has to be recovered from the source
line at the reported column. Scoping this work started with `grep -A1 ... | grep -oE '[A-Z]\\w+'`,
which counts every capitalised word in the context line: it reported `Theme` 1,443 times in a
run where `Theme` was never once the flagged token, and inflated the totals by roughly 2x.
Anything that reads this output by regex over whole lines will be wrong in the same way.

WHAT IT IS FOR
--------------
Two jobs, deliberately in one place so they cannot disagree:

  --report    human-readable summary: categories, worst files, top identifiers.
  --check     the gate. Compares against the baseline and exits non-zero on a regression.

THE `unqualified` CATEGORY IS SPECIAL
-------------------------------------
Every other category is enforced globally: present in the exemption list or the build fails.
`unqualified` cannot be, because a large residue survives any registration work — delegate and
file-scope identifiers (`modelData`, `root`, `index`) whose remedy is
`pragma ComponentBehavior: Bound`, a semantic change rather than a lint fix, and out of scope
here. The current counts are not repeated in this comment; `qml-diagnostics-baseline.json` holds
them, and unlike a comment it cannot drift from what the tool actually reports.

So `unqualified` is enforced PER FILE: files at zero are locked at zero, files above it carry a
ceiling that may only fall. Suppressing the category outright is never an option — it is the
only automated detector for an undeclared QML identifier, which compiles clean and throws only
when its binding is first evaluated. That exact failure shipped in 2.0.1 (#1661).
"""

# PEP 604 annotations (`Path | None`) are used below and are 3.10+ syntax, but CMake's
# Python3_EXECUTABLE on macOS is Xcode's python3.9 — which evaluates annotations eagerly and
# raises TypeError at import, before argparse ever runs. Deferring them keeps the CMake targets
# working on the oldest interpreter that can be picked to run this.
from __future__ import annotations

import argparse
import json
import re
import subprocess
import tempfile
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BASELINE = REPO / "qml-diagnostics-baseline.json"

# Categories not yet cleared, with the occurrence count each currently covers. Any category
# absent from this block fails the gate on its first occurrence, with no count involved — so
# a diagnostic class nobody has seen before cannot arrive quietly.
#
# THIS BLOCK IS HAND-EDITED AND ONLY EVER LOSES ENTRIES. It deliberately does not live in
# qml-diagnostics-baseline.json: that file is regenerated by --update-baseline, and a
# regenerated exemption list is not an exemption list — it would re-bless whatever the tool
# happened to report that day, including a category someone had just finished clearing.
#
# It lives here rather than in CMakeLists.txt, where compiler-diagnostics keeps the equivalent
# -Wno- block, because that block is read by the compiler and this one is read only by the code
# below. Same contract, put where the thing that enforces it can see it.
#
# `unqualified` is NOT eligible for this block and never will be — see the module docstring.
# Its enforcement is per file, through the baseline's clean list and ceilings.
CATEGORY_EXEMPTIONS: dict[str, int] = {
    # Measured on the first full-tree run that completed and accounted for every diagnostic
    # line it produced. Each entry is a ceiling, not a budget.
    "missing-property": 317,
    # Undefined behaviour, per Qt's own wording: setting width/height/anchors/y on an item a
    # layout manages. The remedy is implicitWidth/implicitHeight or Layout.preferredWidth/
    # Height. These were invisible until the parser stopped dropping dotted category names,
    # so they have never been triaged — treat the number as unexamined, not as accepted.
    "Quick.layout-positioning": 254,
    "import": 21,
    "Quick.property-changes-parsed": 5,
    "duplicate-property-binding": 2,
    "unresolved-type": 2,
    "equality-type-coercion": 1,
    "incompatible-type": 1,
}

# Two shapes, and getting either wrong loses diagnostics silently:
#
#   Warning: qml/main.qml:1057:25: Detected height on ... [Quick.layout-positioning]
#   Warning: Type SettingsTabs not declared as singleton in qmldir ... [import]
#
# The location is OPTIONAL — module-level findings have no file to point at. And the category
# is not lowercase-and-hyphens: plugin categories are dotted and capitalised. An earlier
# `[a-z-]+` class rejected exactly those, dropping 264 diagnostics from a 12,862-line run,
# 254 of them real "undefined behavior" layout warnings. The count looked plausible, which is
# why it went unnoticed until two counting methods disagreed.
WARN_RE = re.compile(
    r"^(?:Warning|Error): (?:(?P<path>.+?):(?P<line>\d+):(?P<col>\d+): )?"
    r"(?P<msg>.*?) \[(?P<category>[A-Za-z0-9._-]+)\]$")
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# QML that is deliberately outside the module. Kept to exactly the files that have a reason,
# because the check this suppresses — a .qml on disk that nothing bundles or lints — is one of
# the failure modes this gate exists to catch, and a loose pattern here would switch it off.
NOT_IN_MODULE_BY_DESIGN = {
    # Design-time stubs for the C++ backend, read by Qt Design Studio via de1-qt.qmlproject.
    # Bundling them would ship placeholder values that shadow the real backend types.
    "qml/designer/DE1AppStubs.qml",
}

# Files a RELEASED qmllint cannot analyse at all — not "slowly", not "with false positives",
# but never finishing. Dropped from the run only when --skip-unlintable is passed, which is for
# CI; a developer with a fixed qmllint lints them like anything else and the baseline holds
# their real numbers. Each entry names the upstream fix, so the entry has an expiry condition
# rather than becoming permanent by inattention.
#
# This is the one place where the gate knowingly looks at less than the whole tree, so it is a
# flag and a named set rather than something inferred: a run that silently analysed fewer files
# than it was asked to is the exact failure this script was rewritten to make impossible.
UNLINTABLE_BY_TOOL_BUG: dict[str, str] = {
    "qml/components/layout/items/CustomItem.qml":
        "QQmlJSTypeResolver::merge() is exponential, so qmllint 6.11.1 reaches a 313 GB "
        "footprint on this file and is OOM-killed. Fixed by "
        "https://codereview.qt-project.org/c/qt/qtdeclarative/+/755657 — delete this entry "
        "once CI's Qt carries it.",
}


def relative_to_repo(path: str) -> str:
    """Normalise a path qmllint printed (or Qt's response file listed) to a repo-relative key.

    Qt's response file names sources absolutely, so qmllint echoes absolute paths. The baseline
    is committed and read on other machines and in CI, where the checkout lives somewhere else
    entirely — keys have to be repo-relative or nothing ever matches.
    """
    path = path.replace("\\", "/")
    prefix = str(REPO) + "/"
    return path[len(prefix):] if path.startswith(prefix) else path


def find_qmllint() -> str:
    for c in (
        Path.home() / "Qt/6.11.1/macos/bin/qmllint",
        Path("C:/Qt/6.11.1/msvc2022_64/bin/qmllint.exe"),
    ):
        if c.exists():
            return str(c)
    from shutil import which

    found = which("qmllint")
    if not found:
        sys.exit("qmllint not found. Pass --qmllint <path>.")
    return found


def default_import_path() -> str:
    """Find a build directory containing the generated `Decenza` module.

    CMake passes --import-path explicitly, so this only serves someone running the script by
    hand. Naming a specific build directory here would be wrong for everyone whose kit name
    differs, so find one instead: any directory holding Decenza/qmldir, most recently written
    first. Returns a plausible-looking path when there is no candidate, so the caller's
    "build first" error names something concrete rather than an empty string.
    """
    candidates = sorted(
        (p.parent.parent for p in REPO.glob("build*/**/Decenza/qmldir")),
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )
    return str(candidates[0].relative_to(REPO)) if candidates else "build"


def qml_files() -> list[str]:
    return sorted(str(p.relative_to(REPO)) for p in (REPO / "qml").rglob("*.qml"))


def response_file(import_path: str) -> Path | None:
    """Qt's own generated qmllint argument file, if the build produced one.

    `qt_add_qml_module` emits <build>/.rcc/qmllint/Decenza.rsp holding the exact flags and
    file list Qt's built-in `Decenza_qmllint` target uses. Prefer it over hand-assembled
    arguments: it is generated from the module definition, so it cannot disagree with how the
    module is actually built, and it carries whatever resource and import flags this Qt version
    needs. Guessing at those instead is how a lint run ends up reporting failures that are
    really just a missing flag.
    """
    rsp = REPO / import_path / ".rcc" / "qmllint" / "Decenza.rsp"
    return rsp if rsp.is_file() else None


def split_response(rsp: Path) -> tuple[list[str], list[str]]:
    """Split Qt's response file into (flags, .qml paths).

    The flags have to be reused verbatim — they are what makes the run match how the module is
    really compiled — but the file list has to be splittable, for the reason in run().
    """
    flags, files = [], []
    for line in rsp.read_text().split("\n"):
        entry = line.strip()
        if not entry:
            continue
        # .js counts as an input, not a flag. Qt lints the module's JavaScript too, and treating
        # those seven paths as flags would append them to EVERY batch — their warnings counted
        # once per batch, and their per-file ceilings inflated by however many batches ran.
        (files if entry.endswith((".qml", ".js")) else flags).append(entry)
    return flags, files


def files_from_response(rsp: Path) -> list[str]:
    """The .qml paths Qt's response file actually lints, repo-relative."""
    out = []
    for entry in split_response(rsp)[1]:
        p = Path(entry)
        out.append(str(p.relative_to(REPO)) if p.is_absolute() and p.is_relative_to(REPO) else entry)
    return sorted(out)


def run(qmllint: str, import_path: str, files: list[str], rsp: Path | None,
        raw_out: str | None, batch: int, timeout: int, skip: set[str]) -> str:
    """Lint the tree and return everything qmllint printed. Aborts rather than under-report.

    IN BATCHES, NOT ONE PROCESS, because qmllint 6.11.1 leaks on this corpus: measured at about
    30 GB/minute of Malloc Small, reaching a 313 GB physical footprint before dying at file 185
    of 211. It is not a slow run, it is an unbounded one, and on the way down it drove the whole
    machine into swap.

    That failure is the reason for the returncode check below, which matters more than the
    batching. The single-process run exited without linting the last 26 files, this script did
    not look at the exit status, and the report it printed looked entirely normal — 46 clean
    files, plausible per-category totals. Had it been --update-baseline instead of --report, 26
    never-analysed files would have been recorded as clean and locked at zero, and the gate
    would have gone on defending a number nobody measured. A linter that quietly analyses less
    than it was asked to is worse than one that fails.

    Output goes to a FILE rather than a captured pipe even when the caller did not ask for one:
    qmllint prints nothing until it exits, so a pipe makes a run opaque, and `wc -l` on a
    growing file is the only progress signal there is.
    """
    if rsp:
        flags, all_files = split_response(rsp)
    else:
        flags, all_files = ["-I", import_path], list(files)
    # The response file names sources absolutely and is the authority on what gets linted, so a
    # skip has to be applied HERE and not only to the caller's list — filtering `files` alone
    # would drop the file from the accounting while still handing it to qmllint, which is the
    # worst of both.
    if skip:
        all_files = [f for f in all_files if relative_to_repo(f) not in skip]

    out_path = Path(raw_out) if raw_out else Path(tempfile.gettempdir()) / "qmllint_raw.txt"
    size = batch if batch > 0 else len(all_files)
    chunks = [all_files[i:i + size] for i in range(0, len(all_files), size)]
    done = 0
    with out_path.open("w") as fh:
        for n, chunk in enumerate(chunks, 1):
            try:
                proc = subprocess.run(
                    [qmllint, *flags, *chunk],
                    cwd=REPO,
                    stdout=fh,
                    stderr=subprocess.STDOUT,
                    text=True,
                    timeout=timeout,
                )
            except subprocess.TimeoutExpired:
                # Almost certainly QTBUG: QQmlJSTypeResolver::merge() recurses into itself twice
                # and allocates per node, so a QML function with enough type-merging branches
                # takes exponential time and unbounded memory. Say so, because the symptom on a
                # CI runner is an unexplained hang or an OOM kill on an unrelated change, and
                # nobody would guess the linter from that.
                sys.exit(
                    f"qmllint exceeded {timeout}s on batch {n}/{len(chunks)} "
                    f"({chunk[0] if len(chunk) == 1 else f'{len(chunk)} files from {chunk[0]}'}).\n"
                    f"This is a known qmllint bug, not a hung machine: merge() in "
                    f"QQmlJSTypeResolver is exponential, and qml/components/layout/items/"
                    f"CustomItem.qml crosses the threshold — stock qmllint 6.11.1 reaches a "
                    f"313 GB footprint and is OOM-killed on it.\n"
                    f"Either lint with a fixed qmllint (--qmllint <path>, or "
                    f"-DQMLLINT_EXECUTABLE=<path>), or pass --skip-unlintable to exclude the "
                    f"files listed in UNLINTABLE_BY_TOOL_BUG and check the rest of the tree."
                )
            fh.flush()
            # Negative on POSIX means killed by a signal — SIGKILL here is the OOM killer, and
            # it is exactly the case that must never reach the baseline. A positive code just
            # means "found warnings", which is the normal state of this codebase.
            if proc.returncode < 0:
                sys.exit(
                    f"qmllint was killed by signal {-proc.returncode} on batch {n}/{len(chunks)} "
                    f"({chunk[0]} ...).\n"
                    f"Only {done} of {len(all_files)} files were analysed, so any count from this "
                    f"run understates the tree and any file not reached would look clean.\n"
                    f"Retry with a smaller --batch."
                )
            done += len(chunk)
            print(f"\r  linted {done}/{len(all_files)} files", end="", file=sys.stderr, flush=True)
    print(file=sys.stderr)
    return out_path.read_text(errors="replace")


def parse(output: str) -> tuple[Counter, dict[str, Counter], Counter]:
    """-> (per-category counts, per-file unqualified-identifier counts, per-file totals)"""
    lines = output.split("\n")
    categories: Counter = Counter()
    unqualified: dict[str, Counter] = defaultdict(Counter)
    per_file: Counter = Counter()
    for i, line in enumerate(lines):
        m = WARN_RE.match(line)
        if not m:
            continue
        category = m["category"]
        categories[category] += 1

        path, col = m["path"], m["col"]
        if path is None:
            # A module-level finding with no file to attribute it to (e.g. a qmldir/pragma
            # Singleton mismatch). Still counted per category, which is where it gets enforced;
            # there is simply no per-file ceiling to charge it against.
            continue
        path = relative_to_repo(path)
        per_file[path] += 1
        if category != "unqualified":
            continue
        # Recover the identifier from the source line at the reported column.
        src = lines[i + 1] if i + 1 < len(lines) else ""
        start = int(col) - 1
        tok = IDENT_RE.match(src[start:]) if 0 <= start < len(src) else None
        unqualified[path][tok.group(0) if tok else "<unparsed>"] += 1
    return categories, unqualified, per_file


def build_state(categories: Counter, unqualified: dict, files: list[str]) -> dict:
    counts = {f: sum(unqualified[f].values()) for f in files if unqualified.get(f)}
    return {
        # A generated file that someone will open and try to interpret, so it says what it is.
        "_README": [
            "Generated by scripts/qmllint_report.py --update-baseline. Do not hand-edit.",
            "'clean': files with zero unqualified warnings. They must stay at zero, and a new "
            "QML file joins them automatically — new code never starts with a budget.",
            "'ceilings': files that still have unqualified warnings. These are ceilings, not "
            "budgets: a count may fall, never rise. Most of what is left is delegate and "
            "file-scope identifiers (modelData, root, index, model), whose remedy is "
            "'pragma ComponentBehavior: Bound' plus required properties on delegates — a "
            "semantic change to how a component resolves names, not a lint suppression.",
            "Category exemptions are NOT here. They are hand-edited in the script, because "
            "this file is regenerated and an exemption list that regenerates is not one.",
        ],
        "clean": sorted(f for f in files if f not in counts),
        "ceilings": dict(sorted(counts.items())),
        # Informational only. Category enforcement reads CATEGORY_EXEMPTIONS, never this —
        # see the comment on that block for why a regenerated file must not be the authority.
        "observed_categories": dict(sorted(categories.items())),
    }


def check_fresh(import_path: str, files: list[str]) -> None:
    """Refuse to run against a stale build directory.

    qmllint resolves the `Decenza` module through <import-path>/Decenza/qmldir, whose entries
    point at the build directory's OWN COPY of the QML — not the working tree. So the module
    types it sees are as old as the last build, while the files it analyses are current.

    This is not hypothetical: the first measurement taken for this change ran against a copy a
    few edits behind and reported 11,565 unqualified warnings and 52 clean files. A rebuild and
    an identical command reported 2,795 and 103. A gate that can be wrong by 4x depending on
    when someone last built is not a gate, so being stale is a hard error.

    Compares CONTENT, not mtime. mtime is wrong in both directions here: the build copies with
    `copy_if_different`, so an unchanged file keeps an older timestamp forever, and any git
    operation that rewrites the working tree (a pull, a branch switch) bumps every source mtime
    without changing a byte. An mtime check reported this very tree stale immediately after a
    successful build.
    """
    module_qml = REPO / import_path / "Decenza" / "qml"
    if not module_qml.is_dir():
        sys.exit(
            f"No module QML at {module_qml}. Build first — without it qmllint cannot resolve "
            f"Decenza types, and every module reference is reported as unqualified."
        )
    stale, missing = [], []
    for f in files:
        rel = Path(f).relative_to("qml")
        copy = module_qml / rel
        if not copy.exists():
            # Not in qt_add_qml_module, so there is no build copy to be stale against. Whether
            # that is intentional is the unlisted-file check's business, not this one's.
            if f not in NOT_IN_MODULE_BY_DESIGN:
                missing.append(f)
            continue
        if copy.read_bytes() != (REPO / f).read_bytes():
            stale.append(f)
    if stale:
        sys.exit(
            "Build directory is STALE — these files differ from the copy qmllint will resolve\n"
            "module types against, so the counts would not describe this source:\n"
            + "".join(f"  {f}\n" for f in stale[:10])
            + (f"  ... and {len(stale) - 10} more\n" if len(stale) > 10 else "")
            + "Rebuild, then re-run. (--allow-stale to override.)"
        )
    if missing:
        print(
            f"note: {len(missing)} QML file(s) are not in the module and are linted without "
            f"module context: {', '.join(missing[:3])}"
            + (" ..." if len(missing) > 3 else ""),
            file=sys.stderr,
        )


def cmd_report(state: dict, categories: Counter, unqualified: dict, files: list[str],
               skipped: set[str]) -> int:
    total_unq = sum(sum(c.values()) for c in unqualified.values())
    print(f"QML files: {len(files)}")
    # Every total below is a total OF THE FILES LINTED. Saying so on the same screen as the
    # numbers, rather than only in a note on stderr that a redirect would drop.
    if skipped:
        print(f"NOT LINTED ({len(skipped)}, this qmllint cannot finish them): "
              f"{', '.join(sorted(skipped))}")
    print(f"clean (zero unqualified): {len(state['clean'])}  |  dirty: {len(state['ceilings'])}\n")
    print("by category:")
    for cat, n in categories.most_common():
        print(f"  {n:6d}  {cat}")
    print(f"\nworst files ({total_unq} unqualified total):")
    for f, n in Counter(state["ceilings"]).most_common(10):
        print(f"  {n:6d}  {f}")
    ids: Counter = Counter()
    for c in unqualified.values():
        ids.update(c)
    print("\ntop flagged identifiers:")
    for name, n in ids.most_common(15):
        print(f"  {n:6d}  {name}")
    return 0


def cmd_check(state: dict, skipped: set[str]) -> int:
    if not BASELINE.exists():
        sys.exit(f"No baseline at {BASELINE}. Run with --update-baseline first.")
    base = json.loads(BASELINE.read_text())
    failures: list[str] = []

    # A skipped file produced no diagnostics because it was never linted, so every comparison
    # against its baseline entry would read as an improvement. Drop it from the baseline side
    # too. Note this can only ever weaken the gate, never fire it: nothing below can fail
    # because a file was skipped.
    base_clean = set(base["clean"]) - skipped
    base_ceilings = {f: n for f, n in base["ceilings"].items() if f not in skipped}
    now_ceilings = state["ceilings"]

    # A file on the clean list must stay at zero. This is the rule that would have caught #1661.
    for f in sorted(base_clean & set(now_ceilings)):
        failures.append(
            f"{f}: {now_ceilings[f]} unqualified warning(s) in a file that had none.\n"
            f"    Make the identifier resolvable. Do not add the file to the baseline."
        )

    # A new file starts clean — new code never gets to carry a backlog.
    known = base_clean | set(base["ceilings"])
    for f in sorted(set(now_ceilings) - known):
        failures.append(f"{f}: new QML file with {now_ceilings[f]} unqualified warning(s); new files must be clean.")

    # Ceilings are ceilings, not budgets.
    for f, limit in sorted(base_ceilings.items()):
        now = now_ceilings.get(f, 0)
        if now > limit:
            failures.append(f"{f}: unqualified rose {limit} -> {now}.")

    # Every other category is enforced globally, against the hand-edited block above rather
    # than against anything the baseline file regenerates.
    for cat, n in sorted(state["observed_categories"].items()):
        if cat == "unqualified":
            continue
        if cat not in CATEGORY_EXEMPTIONS:
            failures.append(
                f"category '{cat}': {n} occurrence(s), and the category is not exempt.\n"
                f"    Fix them. Adding an entry to CATEGORY_EXEMPTIONS is for recording an "
                f"existing backlog, not for admitting a new one."
            )
        elif n > CATEGORY_EXEMPTIONS[cat]:
            failures.append(f"category '{cat}' rose {CATEGORY_EXEMPTIONS[cat]} -> {n}.")

    if failures:
        print("QML diagnostics gate FAILED:\n")
        for f in failures:
            print(f"  - {f}")
        print(
            "\nIf you fixed warnings and the counts fell, re-run with --update-baseline "
            "and commit the result."
        )
        return 1

    print(f"QML diagnostics gate passed. clean: {len(state['clean'])}/{len(state['clean']) + len(now_ceilings)}")
    if skipped:
        # Everything below tells the reader a count has FALLEN and should be locked in. None of
        # it can be said from a partial run: the missing files took their diagnostics with them,
        # so a category that "fell" may not have moved at all. Ratcheting the baseline down on
        # that would hand the next complete run a limit nobody's code ever met.
        print(
            f"{len(skipped)} file(s) skipped ({', '.join(sorted(skipped))}), so this run cannot "
            f"say whether any count improved. Re-run without --skip-unlintable to find out."
        )
        return 0

    improved = sum(
        max(0, limit - now_ceilings.get(f, 0)) for f, limit in base_ceilings.items()
    ) + len(set(base_ceilings) - set(now_ceilings))
    if improved:
        print(f"{improved} improvement(s) not yet in the baseline — run --update-baseline to lock them in.")
    # An exemption whose count has reached zero is finished work that nobody has noticed.
    # Say so, or the block keeps its length while its contents mean nothing.
    for cat, limit in sorted(CATEGORY_EXEMPTIONS.items()):
        now = state["observed_categories"].get(cat, 0)
        if now == 0:
            print(f"category '{cat}' is clear — delete its CATEGORY_EXEMPTIONS entry.")
        elif now < limit:
            print(f"category '{cat}' fell {limit} -> {now} — lower its CATEGORY_EXEMPTIONS entry.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--qmllint", default=None)
    ap.add_argument("--import-path", "-I", default=None,
                    help="build directory holding the generated Decenza module "
                         "(default: autodetected)")
    ap.add_argument("--raw-out", default=None, help="also write qmllint's raw output here")
    ap.add_argument("--from-raw", default=None,
                    help="parse an existing qmllint output file instead of linting. For "
                         "re-reading a completed run, or a CI artifact, without paying for it "
                         "again — a full run is expensive enough that re-running it just to "
                         "re-count is worth avoiding.")
    ap.add_argument("--timeout", type=int, default=600,
                    help="seconds before a qmllint process is treated as hung (default 600). "
                         "A released qmllint never finishes this tree unless --skip-unlintable "
                         "is also passed; see run().")
    ap.add_argument("--batch", type=int, default=0,
                    help="files per qmllint process; 0 (the default) means one process for the "
                         "whole tree, which is how Qt's own Decenza_qmllint target runs it. "
                         "BATCHING CHANGES RESULTS: files linted together resolve types from "
                         "their siblings on the command line, so smaller batches invent extra "
                         "import/missing-property warnings (measured: 22 -> 34 and 323 -> 351 "
                         "at --batch 10). It exists only as an escape hatch for a qmllint that "
                         "cannot finish the tree in one process — see the note in run().")
    ap.add_argument("--allow-stale", action="store_true",
                    help="skip the staleness check (for debugging only)")
    ap.add_argument("--skip-unlintable", action="store_true",
                    help="drop the files in UNLINTABLE_BY_TOOL_BUG from the run. For a qmllint "
                         "that cannot finish them at all (CI, until the upstream fix ships); a "
                         "developer with a fixed qmllint should not pass this, and "
                         "--update-baseline refuses it.")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--report", action="store_true", help="human-readable summary (default)")
    g.add_argument("--check", action="store_true", help="gate: fail on regression")
    g.add_argument("--update-baseline", action="store_true")
    args = ap.parse_args()

    if args.skip_unlintable and args.update_baseline:
        sys.exit(
            "--update-baseline refuses --skip-unlintable. The baseline records what every file "
            "in the module measures; writing it from a run that omitted files would drop their "
            "entries, and the next complete run would then see them as new files carrying a "
            "backlog. Regenerate the baseline with a qmllint that can lint the whole tree."
        )

    on_disk = qml_files()
    if not on_disk:
        sys.exit("No QML files found.")
    import_path = args.import_path or default_import_path()
    # --from-raw analyses output captured earlier, so the build directory's state now says
    # nothing about it. Checking freshness would be checking the wrong thing.
    if not args.allow_stale and not args.from_raw:
        check_fresh(import_path, on_disk)

    rsp = response_file(import_path)
    if rsp:
        files = files_from_response(rsp)
        # A .qml on disk that the module does not list is invisible to qmllint AND missing from
        # the app's resources at runtime — CLAUDE.md calls out forgetting the CMakeLists entry as
        # a known footgun. Without this the file would silently count as clean, so the gate would
        # quietly reward the mistake.
        unlisted = sorted(set(on_disk) - set(files) - NOT_IN_MODULE_BY_DESIGN)
        if unlisted:
            print(
                f"warning: {len(unlisted)} QML file(s) exist but are not in the qt_add_qml_module "
                f"list, so they are neither linted nor bundled:\n"
                + "".join(f"  {f}\n" for f in unlisted),
                file=sys.stderr,
            )
    else:
        files = on_disk
        print(
            f"note: no {import_path}/.rcc/qmllint/Decenza.rsp — falling back to a hand-built "
            f"argument list, which may not match how the module is really compiled.",
            file=sys.stderr,
        )
    # After the unlisted check, which is about the module definition and must still see the file,
    # and before anything that counts.
    skipped = sorted(set(files) & set(UNLINTABLE_BY_TOOL_BUG)) if args.skip_unlintable else []
    if skipped:
        files = [f for f in files if f not in set(skipped)]
        print(
            f"note: skipping {len(skipped)} file(s) this qmllint cannot analyse:\n"
            + "".join(f"  {f}\n    {UNLINTABLE_BY_TOOL_BUG[f]}\n" for f in skipped),
            file=sys.stderr,
        )

    if args.from_raw:
        output = Path(args.from_raw).read_text(errors="replace")
        # Guard the exact failure that produced this option: output covering only part of the
        # tree parses perfectly and reports every unreached file as clean. Warnings alone cannot
        # prove coverage — a genuinely clean file prints nothing — so the honest check is that
        # the LAST file of the input list was reached. Files after the truncation point are the
        # ones at risk, and the last one is always among them.
        # `m["path"]` is None for module-level findings (the location group is optional), and
        # this tree produces those — 22 [import] warnings have no file to point at.
        reported = {relative_to_repo(m["path"]) for m in
                    (WARN_RE.match(ln) for ln in output.split("\n")) if m and m["path"]}
        analysed = sorted(reported & set(files))
        if analysed and files and analysed[-1] != files[-1] and files[-1] not in reported:
            tail = files[files.index(analysed[-1]) + 1:]
            print(
                f"warning: {args.from_raw} reports nothing after {analysed[-1]}, and "
                f"{len(tail)} file(s) follow it in the module's own order. If that run was "
                f"truncated rather than those files being clean, they will be recorded as "
                f"clean here.",
                file=sys.stderr,
            )
    else:
        output = run(args.qmllint or find_qmllint(), import_path, files, rsp,
                     args.raw_out, args.batch, args.timeout, set(skipped))
    categories, unqualified, _ = parse(output)
    state = build_state(categories, unqualified, files)

    if args.check:
        return cmd_check(state, set(skipped))
    if args.update_baseline:
        BASELINE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
        print(
            f"Baseline written: {len(state['clean'])} clean, "
            f"{len(state['ceilings'])} with ceilings, {len(state['observed_categories'])} categories."
        )
        return 0
    return cmd_report(state, categories, unqualified, files, set(skipped))


if __name__ == "__main__":
    sys.exit(main())
